import { existsSync, readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const dir = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(dir, '../../../..')

const generalSlugs = [
  'julius-caesar-general-v1',
  'alexander-general-v1',
  'hannibal-barca-general-v1',
  'napoleon-bonaparte-general-v1',
  'saladin-general-v1',
  'genghis-khan-general-v1',
]

describe('Council of Strategists chamber', () => {
  it('wires the local planning room with six generals, votes, and Hermes handoff only', () => {
    const source = readFileSync(path.join(dir, 'CouncilChamberSurface.tsx'), 'utf8')
    const css = readFileSync(path.join(dir, 'council-chamber-surface.css'), 'utf8')
    const routeSource = readFileSync(path.join(dir, 'LivingWarRoomV3.tsx'), 'utf8')

    expect(source).toContain('data-council-room="strategists-v1"')
    expect(source).toContain('data-council-decision-packet')
    expect(source).toContain('data-council-motion-state')
    expect(source).toContain('data-council-handoff-unlocked')
    expect(source).toContain('data-council-responses-visible')
    expect(source).toContain('data-council-reactions-visible')
    expect(source).toContain('data-council-reactions')
    expect(source).toContain('COUNCIL_PERSISTENCE_STORAGE_KEY')
    expect(source).toContain('COUNCIL_ARCHIVE_STORAGE_KEY')
    expect(source).toContain('loadStoredCouncilState')
    expect(source).toContain('loadCouncilArchive')
    expect(source).toContain('upsertCouncilArchiveSession')
    expect(source).toContain('startNewDiscussion')
    expect(source).toContain('restoreArchivedDiscussion')
    expect(source).toContain('saveStoredCouncilState')
    expect(source).toContain('clearStoredCouncilState')
    expect(source).toContain('data-council-persistence="local-storage-v1"')
    expect(source).toContain('data-council-archive="local-restore-v1"')
    expect(source).toContain('data-council-start-new-discussion="true"')
    expect(source).toContain('data-council-archive-toggle="true"')
    expect(source).toContain('data-council-restore-archive="true"')
    expect(source).toContain('דיון חדש')
    expect(source).toContain('ארכיון דיונים')
    expect(source).toContain('data-council-persisted-state')
    expect(source).toContain('אפס')
    expect(source).toContain('data-council-idle-state')
    expect(source).toContain('dormant-roaming')
    expect(source).toContain('data-council-summary-first="true"')
    expect(source).toContain('data-council-user-prompt-visible="true"')
    expect(source).toContain('data-council-static-copy="details-only"')
    expect(source).toContain('data-council-vote-labels="for-neutral-against-abstain"')
    expect(source).toContain('data-council-design-pass="command-rail-v2"')
    expect(source).toContain('data-council-live-decision-visual="vote-board-v1"')
    expect(source).toContain('data-council-live-vote-count')
    expect(source).toContain('data-council-live-vote-board="true"')
    expect(source).toContain('data-council-visual-voting="decision-table-live-v1"')
    expect(source).toContain('data-council-decision-ring="support-neutral-against-abstain"')
    expect(source).toContain('data-council-decision-timeline="live-vote-flow-v1"')
    expect(source).toContain('data-council-timeline-step={step.key}')
    expect(source).toContain('data-council-vote-lanes="true"')
    expect(source).toContain('data-council-vote-phase={phase}')
    expect(source).toContain('votePhaseLabel(phase)')
    expect(source).toContain('voteCountsFromTurns')
    expect(source).toContain('currentDecisionTurnByGeneral')
    expect(source).toContain('visibleVoteGeneralIds')
    expect(source).toContain('pendingVoteGeneralId')
    expect(source).toContain('data-council-minimal-rescue="true"')
    expect(source).toContain('data-council-minimal-mode={minimalMode}')
    expect(source).toContain("data-council-primary-action={minimalMode === 'start' ? 'open-council'")
    expect(source).toContain("type CouncilMinimalView = 'council' | 'advisor'")
    expect(source).toContain("const minimalMode = session ? minimalView : 'start'")
    expect(source).toContain('selectAdvisor(general.id)')
    expect(source).toContain('setMinimalView(\'advisor\')')
    expect(source).toContain('setMinimalView(\'council\')')
    expect(source).toContain('data-council-question-card="true"')
    expect(source).toContain('data-council-consensus-card="true"')
    expect(source).toContain('data-council-recommendation-card="true"')
    expect(source).toContain('data-council-planning-workspace="true"')
    expect(source).toContain('data-council-planning-guide="true"')
    expect(source).toContain('data-council-advisor-consultation="true"')
    expect(source).toContain('data-council-minimal-start="true"')
    expect(source).toContain('data-council-minimal-council="true"')
    expect(source).toContain('data-council-minimal-advisor="true"')
    expect(source).toContain('data-council-active-advisor={activeGeneral.id}')
    expect(source).toContain('data-council-consultation-count={completedConsultations}')
    expect(source).toContain('advisorChatMessagesFor')
    expect(source).toContain('messageBelongsToAdvisor')
    expect(source).toContain('advisorChatRef')
    expect(source).toContain('data-council-right-space-fill="advisor-dock-v1"')
    expect(source).toContain('data-council-advisor-chat="portrait-bubbles-v1"')
    expect(source).toContain('data-council-advisor-chat-log="true"')
    expect(source).toContain('data-council-advisor-composer="true"')
    expect(source).toContain('data-council-advisor-avatar="active-chat"')
    expect(source).toContain('data-council-advisor-avatar="right-space"')
    expect(source).toContain('data-council-advisor-vote-state')
    expect(source).toContain('council-chamber__advisor-dock-vote')
    expect(source).toContain('OperatorRoundBubble')
    expect(source).toContain('מה מתכננים?')
    expect(source).toContain('מסקנת מועצה')
    expect(source).toContain('בחר יועץ לשיחה')
    expect(source).toContain('שיחה עם יועץ')
    expect(source).toContain('שאל יועץ אחד')
    expect(source).toContain('חזור למועצה')
    expect(source).toContain('דלג ליועץ הבא')
    expect(source).toContain('סיימתי')
    expect(source).toContain('שלח להרמס')
    expect(source).toContain('פרק את זה לתוכנית עבודה קצרה לפי שלבים')
    expect(source).not.toContain('REAL AI COUNCIL V1')
    expect(source).not.toContain('Controlled one-shot per general · Obsidian context · no fake answers')
    expect(source).not.toContain('מסויג')
    expect(source).not.toContain('GUARDED')
    expect(source).not.toContain('HOLD —')
    expect(source).toContain('data-council-personality-profiles="controlled-real-ai-v1"')
    expect(source).toContain('data-council-avatar')
    expect(source).toContain('data-council-avatar-source={general ? \'runtime-portrait\' : \'initials\'}')
    expect(source).toContain('data-council-typing-active')
    expect(source).toContain('data-council-typing-general')
    expect(source).toContain('data-council-response-mode={councilResponseMode}')
    expect(source).toContain('data-council-ai-mode={councilAiMode}')
    expect(source).toContain('data-council-ready-for-real-ai="true"')
    expect(source).toContain('data-council-no-fake-responses')
    expect(source).toContain('data-council-context-packet')
    expect(source).toContain('data-council-drilldown="true"')
    expect(source).toContain('/api/war-room/council/run')
    expect(source).toContain('/api/war-room/council/follow-up')
    expect(source).toContain('fetchRealCouncilSession')
    expect(source).toContain('fetchRealCouncilFollowUp')
    expect(source).toContain('if (!response.ok)')
    expect(source).not.toContain('!response.ok || !data.ok')
    expect(source).toContain('if (response.ok && data.turn)')
    expect(source).not.toContain('!data.ok || !data.turn')
    expect(source).toContain('COUNCIL_LOCAL_THINKING_MIN_MS = 1_450')
    expect(source).toContain('COUNCIL_FAST_PASS_AGENT_TIMEOUT_MS = 45_000')
    expect(source).toContain('COUNCIL_FOLLOW_UP_AGENT_TIMEOUT_MS = 45_000')
    expect(source).toContain("COUNCIL_FAST_PASS_AGENT_IDS = ['council-julius', 'council-alexander', 'council-hannibal']")
    expect(source).toContain('includePeerVote: false')
    expect(source).toContain('timeoutMs: COUNCIL_FAST_PASS_AGENT_TIMEOUT_MS')
    expect(source).toContain('timeoutMs: COUNCIL_FOLLOW_UP_AGENT_TIMEOUT_MS')
    expect(source).toContain('fetchCouncilJsonWithTimeout')
    expect(source).toContain('Council API timed out after')
    expect(source).toContain('scrollTop = node.scrollHeight')
    expect(css).toContain('font-family: ui-sans-serif')
    expect(css).toContain('Council V2 — summary-first decision UI')
    expect(css).toContain('Council V3 — persistence-first decision brief')
    expect(css).toContain('Council V3 layout fix')
    expect(css).toContain('Council V4 guided planning flow')
    expect(css).toContain('Council V4 flow order fix')
    expect(css).toContain('Council V4 desktop split flow')
    expect(css).toContain('Council V4 question compact fix')
    expect(css).toContain('Council V4 first-screen fit')
    expect(css).toContain('Council Minimal Rescue V1')
    expect(css).toContain('Council Minimal Rescue V1 compact selector fix')
    expect(css).toContain('Council Minimal Rescue V1 advisor dock row fix')
    expect(css).toContain('Council Minimal Rescue V1 advisor chip label trim')
    expect(css).toContain('Council Minimal Rescue V1 single-column override')
    expect(css).toContain('Council Minimal Rescue V1 advisor fit fix')
    expect(css).toContain('Council Minimal Rescue V1 tool grid fit')
    expect(css).toContain('Council Minimal Rescue V1 advisor dock all-visible grid')
    expect(css).toContain('Council Minimal Rescue V1 advisor vertical fit')
    expect(source).toContain('data-council-design-pass="command-rail-v2"')
    expect(source).toContain('data-council-command-rail="v2"')
    expect(source).toContain('data-council-ask-whole-council="true"')
    expect(source).toContain('data-council-step-plan="true"')
    expect(source).toContain('COUNCIL_STEP_PLAN_PROMPT')
    expect(source).toContain('askWholeCouncilFollowUp')
    expect(source).toContain('continue-council-or-plan')
    expect(css).toContain('Council Command Rail V2')
    expect(css).toContain('Council Live Vote Board V1')
    expect(css).toContain('council-chamber__live-vote-board')
    expect(css).toContain('council-chamber__vote-meter')
    expect(css).toContain('council-chamber__decision-timeline')
    expect(css).toContain('council-chamber__vote-lane')
    expect(css).toContain('council-live-vote-thinking')
    expect(css).toContain('data-council-live-decision-visual="vote-board-v1"')
    expect(css).toContain('Council Command Rail V2 fit refinement')
    expect(css).toContain('Council Archive + Clean Stage V1')
    expect(css).toContain('Council Right Workspace Fill V1')
    expect(css).toContain('Council Advisor Dock responsive density')
    expect(css).toContain('council-chamber__advisor-dock')
    expect(css).toContain('council-chamber__advisor-dock-card')
    expect(css).toContain('council-chamber__advisor-dock-vote')
    expect(css).toContain('council-chamber__advisor-chat-log')
    expect(css).toContain('council-chamber__advisor-composer')
    expect(css).toContain('council-chamber__advisor-chat-portrait')
    expect(css).toContain('data-council-advisor-chat="portrait-bubbles-v1"')
    expect(css).toContain('data-council-command-rail="v2"')
    expect(css).toContain('council-chamber__command-rail')
    expect(css).toContain('council-chamber__command-actions')
    expect(css).toContain('clip-path: polygon(10px 0, 100% 0, calc(100% - 10px) 100%, 0 100%)')
    expect(css).toContain('data-council-minimal-rescue="true"')
    expect(css).toContain('data-council-minimal-mode="start"')
    expect(css).toContain('data-council-minimal-mode="council"')
    expect(css).toContain('data-council-minimal-mode="advisor"')
    expect(css).toContain('chat-first planning room')
    expect(css).toContain('council-chamber__recommendation-proof')
    expect(css).toContain('council-chamber__general-card small')
    expect(css).toContain('data-council-design-pass="decision-brief-v3"')
    expect(css).toContain('council-chamber__question-card')
    expect(css).toContain('council-chamber__planning-guide')
    expect(css).toContain('council-chamber__prompt-chips')
    expect(css).toContain('council-chamber__operator-head')
    expect(css).toContain('council-chamber__consensus')
    expect(css).toContain('council-chamber__general-card')
    expect(css).toContain('council-chamber__transcript:not([open]) .council-chamber__chat { display: none; }')
    expect(css).toContain('council-chamber__reactions')
    expect(css).toContain('council-chamber__avatar')
    expect(css).toContain('council-chamber__avatar--portrait')
    expect(css).toContain('grid-template-columns: minmax(500px, 0.94fr) minmax(540px, 1.06fr)')
    expect(css).toContain('council-chamber__typing')
    expect(css).toContain('council-chamber__reply-context')
    expect(css).toContain('council-chamber__selected-meta')
    expect(css).toContain('council-chamber__bubble--dlv')
    expect(css).toContain('council-slow-roam')
    expect(css).toContain('council-running-to-table')
    expect(css).toContain('council-chair-sitting')
    expect(css).toContain('background-size: 800% 900%')
    expect(routeSource).toContain('selectedStationUsesCouncilWorkspace')
    expect(routeSource).toContain('councilCleanStageActive')
    expect(routeSource).toContain('data-council-clean-stage={councilCleanStageActive ? \'true\' : \'false\'}')
    expect(routeSource).toContain('!councilCleanStageActive &&')
    expect(routeSource).toContain('transferCouncilDecisionToHermes')
    expect(routeSource).toContain('Council packet ready for Hermes Command')
    expect(routeSource).toContain("visualStatus === 'council-room-general'")
    expect(routeSource).toContain("onClick={() => focusRoom('council-strategists')}")

    for (const slug of generalSlugs) {
      expect(source).toContain(slug)
      expect(existsSync(path.join(repoRoot, 'public/war-room/living-v3/generals-council', slug, 'spritesheet.png'))).toBe(true)
      expect(existsSync(path.join(repoRoot, 'public/war-room/living-v3/generals-council', slug, 'runtime', 'walk.png'))).toBe(true)
      expect(existsSync(path.join(repoRoot, 'public/war-room/living-v3/generals-council', slug, 'runtime', 'sit.png'))).toBe(true)
    }
  })
})
