import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

describe('Goblin Analytics shell', () => {
  it('renames the Agora room and station without changing their stable IDs', () => {
    const dir = path.dirname(fileURLToPath(import.meta.url))
    const source = readFileSync(path.join(dir, 'LivingWarRoomV3.tsx'), 'utf8')
    const shell = readFileSync(path.join(dir, 'GoblinAnalyticsShell.tsx'), 'utf8')
    const routeSource = readFileSync(path.join(dir, '../war-room-screen.tsx'), 'utf8')
    const rootSource = readFileSync(path.join(dir, '../../../routes/__root.tsx'), 'utf8')
    const contract = readFileSync(path.join(dir, '../../../lib/war-room/living-v3/living-v3-contract.ts'), 'utf8')

    expect(contract).toContain("id: 'agora-opportunity'")
    expect(contract).toContain("label: 'Goblin Analytics'")
    expect(contract).toContain("id: 'agora-intake'")
    expect(contract).toContain("label: 'Goblin Radar Desk'")
    expect(contract).not.toContain("label: 'Agora of Opportunity'")
    expect(contract).not.toContain("label: 'Opportunity Stalls'")

    expect(source).toContain("const selectedStationIsGoblin = selectedStation?.id === 'agora-intake'")
    expect(source).toContain('goblinFocusMode = false')
    expect(source).toContain("? { kind: 'station', id: 'agora-intake' }")
    expect(source).toContain("? fitLivingV3RoomCamera('agora-opportunity', INITIAL_VIEWPORT)")
    expect(source).toContain("data-goblin-focus-mode={goblinFocusMode ? 'true' : 'false'}")
    expect(routeSource).toContain('const goblinFocusMode = isTruthyWarRoomFlag(routeSearch.goblinOps) || isTruthyWarRoomFlag(routeSearch.goblinFocus)')
    expect(routeSource).toContain('goblinFocusMode={goblinFocusMode}')
    expect(rootSource).toContain('isTruthyWarRoomFlag(routeSearch.goblinOps)')
    expect(source).toContain('<GoblinAnalyticsShell />')
    expect(source).toContain('Goblin intelligence room · read-only · no Etsy writes or supplier messages')

    expect(shell).toContain('data-goblin-analytics-shell="api-v3-decision-workbench"')
    expect(shell).toContain('data-professional-workbench="live-operator-table"')
    expect(shell).toContain('data-goblin-api-status={apiState.status}')
    expect(source).toContain('selectedStationUsesGoblinWorkspace')
    expect(source).toContain('living-v3--goblin-primary-workspace')
    expect(source).toContain('data-goblin-primary-workspace-active={selectedStationUsesGoblinWorkspace ? \'true\' : \'false\'}')
    expect(source).toContain('<GoblinAnalyticsShell\n          variant="primary"')
    expect(source).toContain('!selectedStationUsesCouncilWorkspace && !selectedStationUsesOracleWorkspace)')
    expect(shell).toContain('data-goblin-workbench-open={primaryMode || workbenchOpen ? \'true\' : \'false\'}')
    expect(shell).toContain('data-goblin-workbench-mode={primaryMode ? \'primary\' : \'station\'}')
    expect(shell).toContain('data-room-ownership="goblin-discovery-and-research"')
    expect(shell).toContain('data-goblin-primary-view={primaryView}')
    expect(shell).toContain('data-goblin-view-tabs="radar-research"')
    expect(shell).toContain('<ResearchAtlasSurface')
    expect(shell).toContain('embedded')
    expect(shell).toContain('data-room-ownership="goblin-discovery-and-research"')
    expect(shell).toContain('data-goblin-workbench-modal')
    expect(shell).toContain('goblin-workbench--embedded')
    expect(shell).toContain("import { createPortal } from 'react-dom'")
    expect(shell).toContain('createPortal(workbenchSurface, document.body)')
    expect(shell).toContain('data-goblin-dossier-product={selectedProduct.id}')
    expect(shell).toContain('data-goblin-dive-panel={panel}')
    expect(shell).toContain('data-goblin-dive-tabs="true"')
    expect(shell).toContain('data-goblin-product-filters="true"')
    expect(shell).toContain('data-goblin-db-source={snapshot.source}')
    expect(shell).toContain('data-goblin-database-foundation="workspace-core"')
    expect(shell).toContain('data-goblin-db-provider={snapshot?.database.provider ?? \'pending\'}')
    expect(shell).toContain('Search product or source shop')
    expect(shell).toContain('data-goblin-three-second-summary="true"')
    expect(shell).toContain('data-goblin-live-pipeline="true"')
    expect(shell).toContain('data-goblin-agent-aware="true"')
    expect(shell).toContain('Agent auto-detect')
    expect(shell).toContain("fetch('/api/war-room/workspace-kernel/state'")
    expect(shell).toContain('data-goblin-readback-state={readbackStatus}')
    expect(shell).toContain('idle refresh every 60s')
    expect(shell).toContain('setInterval(() => setRefreshNonce')
    expect(shell).toContain('data-goblin-source-shops="true"')
    expect(shell).toContain('Open source shop')
    expect(shell).toContain('No matching seed')
    expect(shell).toContain('Supabase live readback')
    expect(shell).toContain('workspace_core')
    expect(shell).toContain('goblin_analytics')
    expect(shell).toContain('data-read-only="true"')
    expect(shell).toContain('data-no-etsy-writes="true"')
    expect(shell).toContain('data-no-supplier-messages="true"')
    expect(shell).toContain('Verified GREEN only')
    expect(shell).toContain("fetch('/api/war-room/goblin-analytics'")
    expect(shell).toContain("method: 'GET'")
    expect(shell).toContain('Goblin Control Table')
    expect(shell).toContain('WOW לתקיפה')
    expect(shell).toContain('data-goblin-board="operator-table"')
    expect(shell).not.toContain("method: 'POST'")
  })
})
