import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const dir = path.dirname(fileURLToPath(import.meta.url))

function read(name: string) {
  return readFileSync(path.join(dir, name), 'utf8')
}

describe('Hermes Command action cockpit and agent controls', () => {
  it('keeps agent-control contracts while making the purpose-built cockpit primary', () => {
    const source = read('LivingWarRoomV3.tsx')
    const cockpit = read('HermesCommandCockpit.tsx')
    const cockpitCss = read('hermes-command-cockpit.css')

    expect(source).toContain("import { HermesCommandCockpit } from './HermesCommandCockpit'")
    expect(source).toContain('data-command-desk-layout="action-v2"')
    expect(source).toContain('<HermesCommandCockpit')
    expect(source).toContain('sourceDetails={(')
    expect(source).toContain('title: hermesCommandTaskTitle(run)')

    expect(source).toContain("const selectedStationIsHermesCommand = selectedStation?.id === 'command-table'")
    expect(source).toContain("const selectedStationIsMissionControl = selectedStation?.id === 'mission-router'")
    expect(source).not.toContain("selectedStation?.id === 'approval-dais'")
    expect(source).toContain("surfaceMode={selectedStationIsMissionControl ? 'mission-control' : 'command'}")
    expect(cockpit).toContain("data-hermes-tool={surfaceMode === 'mission-control' ? 'mission-control' : 'hermes-command'}")
    expect(cockpit).toContain("data-hermes-ui-contract={surfaceMode === 'mission-control' ? 'mission-control-v1' : 'hermes-command-v1'}")
    expect(cockpit).toContain('data-command-bridge-region="threads"')
    expect(cockpit).toContain('data-command-bridge-region="workbench"')
    expect(cockpit).toContain('data-command-bridge-region="mission-tasks"')
    expect(cockpit).toContain('data-command-bridge-region="mission-agents"')
    expect(cockpit).toContain('className="hermes-command-cockpit__conversation"')
    expect(cockpit).toContain('className="hermes-command-cockpit__composer"')
    expect(cockpit).toContain('className="hermes-command-cockpit__result')
    expect(cockpit).toContain('/war-room/olympus-command/hermes-90frame-v1/processed/hermes-model.png')
    expect(cockpit).toContain('להתייעץ עם המועצה?')
    expect(cockpit).toContain('התייעץ')
    expect(cockpit).toContain('לא עכשיו')
    expect(cockpit).not.toContain('פעולות חיצוניות נעולות עד אישור DLV')
    expect(cockpit).not.toContain('>נעול<')
    expect(cockpit).toContain('<summary>פרטים</summary>')

    expect(cockpitCss).toContain('.hermes-command-cockpit__conversation')
    expect(cockpitCss).toContain('.hermes-command-cockpit__composer')
    expect(cockpitCss).toContain('.hermes-command-cockpit__threads')
    expect(cockpitCss).toContain('.hermes-command-cockpit__workbench')
    expect(cockpitCss).toContain('.hermes-command-cockpit__operations')
    expect(cockpitCss).toContain('.living-v3__command-side-stack--collapsed')
    expect(cockpitCss).toContain('@media (min-width: 760px)')
    expect(cockpitCss).toContain('@media (prefers-reduced-motion: reduce)')
    expect(source).not.toContain('data-command-quiet-status="user-first-v1"')
    expect(source).not.toContain('className="living-v3__manager-proof"')

    expect(source).toContain('type CommandAgentControlRow')
    expect(source).toContain('function commandAgentStatusTone')
    expect(source).toContain('const commandAgentControlRoster = useMemo<Array<CommandAgentControlRow>>')
    expect(source).toContain('data-hermes-agent-control-tool="status-control-v1"')
    expect(source).toContain('data-agent-control-count={agentRoster.length}')
    expect(source).toContain('className="living-v3__agent-control-row-main"')
    expect(source).toContain('className="living-v3__agent-control-active-actions"')
    expect(source).toContain('data-agent-control-card={agent.agentId}')
    expect(source).toContain('data-agent-control-talk={activeRosterRow.agentId}')
    expect(source).toContain('data-agent-control-focus={activeRosterRow.agentId}')
    expect(source).toContain('data-agent-control-work={activeRosterRow.agentId}')
    expect(source).toContain('data-agent-control-rest={activeRosterRow.agentId}')
    expect(source).toContain('data-agent-control-run={profile.agentId}')
    expect(source).toContain('const commandActionAgentLabel = agentRoster.find((agent) => agent.agentId === actionRun.assignedAgentId)?.label ?? actionRun.assignedAgentId')
    expect(source).toContain('commandActionAgentLabel,')
    expect(source).not.toContain('activeRosterRow ? activeRosterRow.label : undefined')
    expect(source).toContain('onTalkAgent={openAgentControlChat}')
    expect(source).toContain('onFocusAgent={focusAgentFromCommandControl}')
    expect(source).toContain('onAssignAgentPrimaryStation={assignAgentPrimaryStationFromCommand}')
    expect(source).toContain('onRestAgent={restAgentFromCommandControl}')
    expect(source).toContain('onRunControlledAgent={activateControlledAgentRun}')
  })

  it('starts Council only after DLV approval and clears the previous run before the new one', () => {
    const source = read('LivingWarRoomV3.tsx')
    const council = read('CouncilChamberSurface.tsx')
    const approvalStart = source.indexOf('function approveCouncilConsultation()')
    const skipStart = source.indexOf('function skipCouncilConsultation()')
    const approvalBlock = source.slice(approvalStart, skipStart)

    expect(approvalStart).toBeGreaterThan(-1)
    expect(approvalBlock).toContain("status !== 'waiting_operator'")
    expect(approvalBlock).toContain('setCouncilLaunchRequest({')
    expect(approvalBlock).toContain('autoStart: true')
    expect(council).toContain('consumedLaunchRequestRef')
    expect(council).toContain('if (!request || consumedLaunchRequestRef.current === request.requestId || councilRunPending) return')
    const deleteAwait = council.indexOf("await fetch('/api/war-room/council/run'")
    const conveneAwait = council.indexOf('await conveneCouncilTopic(askedTopic)', deleteAwait)
    expect(deleteAwait).toBeGreaterThan(-1)
    expect(conveneAwait).toBeGreaterThan(deleteAwait)
  })
})
