import type {
  WorkspaceApprovalPolicy,
  WorkspaceBlueprint,
  WorkspaceBlueprintId,
  WorkspaceDomain,
  WorkspaceRiskClass,
  WorkspaceWorkerProfile,
} from './contracts'

export const WORKSPACE_KERNEL_LOCKED_ACTIONS = [
  'live Etsy upload/draft/publish/edit/renew/customer action',
  'supplier message or purchase',
  'paid ShotLab or generation spend',
  'Google private read/write or Sheet write',
  'browser automation on logged-in sites',
  'Discord send outside an approved delivery path',
  'printer control or physical production',
  'worker fan-out or uncontrolled runner spawn',
]

const riskOrder: Array<WorkspaceRiskClass> = [
  'R0_LOCAL_VIEW',
  'R1_LOCAL_WRITE',
  'R2_EXTERNAL_READ',
  'R3_EXTERNAL_WRITE',
  'R4_COST_OR_ACCOUNT',
  'R5_DESTRUCTIVE',
]

export function riskAtLeast(riskClass: WorkspaceRiskClass, threshold: WorkspaceRiskClass) {
  return riskOrder.indexOf(riskClass) >= riskOrder.indexOf(threshold)
}

function approvalPolicy(mode: WorkspaceApprovalPolicy['mode'], reason: string): WorkspaceApprovalPolicy {
  return {
    mode,
    reason,
    requiredRiskClasses: mode === 'not_required'
      ? []
      : ['R3_EXTERNAL_WRITE', 'R4_COST_OR_ACCOUNT', 'R5_DESTRUCTIVE'],
  }
}

export const WORKSPACE_DOMAIN_ROOM_MAP: Record<WorkspaceDomain, { roomId: WorkspaceBlueprint['roomId']; label: string }> = {
  command: { roomId: 'olympus-command', label: 'Olympus Command' },
  'data-vault': { roomId: 'atlantis-vault', label: 'Atlantis Vault' },
  etsy: { roomId: 'etsy-market-lab', label: 'Etsy Market Lab' },
  shotlab: { roomId: 'etsy-market-lab', label: 'Etsy Market Lab / ShotLab Prep' },
  'seo-alura': { roomId: 'etsy-market-lab', label: 'Etsy Market Lab / SEO Metrics' },
  supplier: { roomId: 'etsy-market-lab', label: 'Etsy Market Lab / Source Truth' },
  'cad-3d-print': { roomId: 'terra-forge', label: 'Terra Forge' },
  'content-news': { roomId: 'gateway-cockpit', label: 'Gateway Cockpit' },
  'gateway-discord': { roomId: 'gateway-cockpit', label: 'Gateway Cockpit' },
  approval: { roomId: 'olympus-command', label: 'Olympus Command / Approval Dais' },
  'agent-ops': { roomId: 'council-strategists', label: 'Council of Strategists' },
}

const COUNCIL_PROFILE_LOCKED_ACTIONS = [
  ...WORKSPACE_KERNEL_LOCKED_ACTIONS,
  "a general using another general's Hermes profile",
  'background council daemon work',
  'council vote without a real bounded one-shot result',
]

function councilGeneralProfile(input: {
  profileId: WorkspaceWorkerProfile['profileId']
  agentId: NonNullable<WorkspaceWorkerProfile['agentId']>
  label: string
  hermesProfileId: string
}): WorkspaceWorkerProfile {
  return {
    profileId: input.profileId,
    label: input.label,
    roomId: 'council-strategists',
    agentId: input.agentId,
    connected: true,
    approvedControlledRunner: true,
    hermesProfileId: input.hermesProfileId,
    independentProfile: true,
    profileScope: 'council-general',
    localOnly: true,
    usageAllowed: false,
    workerSpawnAllowed: false,
    lockedActions: COUNCIL_PROFILE_LOCKED_ACTIONS,
  }
}

export const WORKSPACE_WORKER_PROFILES: Array<WorkspaceWorkerProfile> = [
  {
    profileId: 'hermes-manager',
    label: 'Hermes Manager',
    roomId: 'olympus-command',
    agentId: 'hermes',
    connected: false,
    approvedControlledRunner: false,
    localOnly: true,
    usageAllowed: false,
    workerSpawnAllowed: false,
    lockedActions: WORKSPACE_KERNEL_LOCKED_ACTIONS,
  },
  {
    profileId: 'chatgpt-5-5-manager',
    label: 'ChatGPT 5.5 Manager Profile',
    roomId: 'council-strategists',
    connected: false,
    approvedControlledRunner: false,
    localOnly: true,
    usageAllowed: false,
    workerSpawnAllowed: false,
    lockedActions: WORKSPACE_KERNEL_LOCKED_ACTIONS,
  },
  {
    profileId: 'chatgpt-5-3-fast-worker',
    label: 'ChatGPT 5.3 Fast Worker Profile',
    roomId: 'council-strategists',
    connected: false,
    approvedControlledRunner: false,
    localOnly: true,
    usageAllowed: false,
    workerSpawnAllowed: false,
    lockedActions: WORKSPACE_KERNEL_LOCKED_ACTIONS,
  },
  {
    profileId: 'codex-ui-builder',
    label: 'Codex UI Builder',
    roomId: 'daedalus-workshop',
    connected: false,
    approvedControlledRunner: false,
    localOnly: true,
    usageAllowed: false,
    workerSpawnAllowed: false,
    lockedActions: WORKSPACE_KERNEL_LOCKED_ACTIONS,
  },
  {
    profileId: 'kimi-code-worker',
    label: 'Kimi Code Worker Profile',
    roomId: 'council-strategists',
    connected: false,
    approvedControlledRunner: false,
    localOnly: true,
    usageAllowed: false,
    workerSpawnAllowed: false,
    lockedActions: WORKSPACE_KERNEL_LOCKED_ACTIONS,
  },
  {
    profileId: 'claude-reviewer-pending-approval',
    label: 'Claude Reviewer Pending Approval',
    roomId: 'council-strategists',
    connected: false,
    approvedControlledRunner: false,
    localOnly: true,
    usageAllowed: false,
    workerSpawnAllowed: false,
    lockedActions: WORKSPACE_KERNEL_LOCKED_ACTIONS,
  },
  councilGeneralProfile({
    profileId: 'council-julius',
    agentId: 'julius',
    label: 'Julius Council Profile',
    hermesProfileId: 'julius',
  }),
  councilGeneralProfile({
    profileId: 'council-alexander',
    agentId: 'alexander',
    label: 'Alexander Council Profile',
    hermesProfileId: 'alexander',
  }),
  councilGeneralProfile({
    profileId: 'council-napoleon',
    agentId: 'napoleon',
    label: 'Napoleon Council Profile',
    hermesProfileId: 'napoleon',
  }),
  councilGeneralProfile({
    profileId: 'council-saladin',
    agentId: 'saladin',
    label: 'Saladin Council Profile',
    hermesProfileId: 'saladin',
  }),
  councilGeneralProfile({
    profileId: 'council-genghis',
    agentId: 'genghis',
    label: 'Genghis Council Profile',
    hermesProfileId: 'genghis',
  }),
  councilGeneralProfile({
    profileId: 'council-hannibal',
    agentId: 'hannibal',
    label: 'Hannibal Council Profile',
    hermesProfileId: 'hannibal',
  }),
  {
    profileId: 'controlled-hermes-v1',
    label: 'Controlled Hermes V1',
    roomId: 'etsy-market-lab',
    agentId: 'loki',
    connected: true,
    approvedControlledRunner: true,
    localOnly: true,
    usageAllowed: false,
    workerSpawnAllowed: false,
    lockedActions: WORKSPACE_KERNEL_LOCKED_ACTIONS,
  },
  {
    profileId: 'controlled-scout-v2',
    label: 'Controlled Loki Scout V2',
    roomId: 'etsy-market-lab',
    agentId: 'loki',
    connected: true,
    approvedControlledRunner: true,
    localOnly: true,
    usageAllowed: false,
    workerSpawnAllowed: false,
    lockedActions: WORKSPACE_KERNEL_LOCKED_ACTIONS,
  },
  {
    profileId: 'controlled-terra-v1',
    label: 'Controlled Terra 3D Print Operator',
    roomId: 'terra-forge',
    agentId: 'terra',
    connected: true,
    approvedControlledRunner: true,
    localOnly: true,
    usageAllowed: false,
    workerSpawnAllowed: false,
    lockedActions: WORKSPACE_KERNEL_LOCKED_ACTIONS,
  },
  {
    profileId: 'controlled-poseidon-vault-v1',
    label: 'Poseidon Atlantis Vault Mind',
    roomId: 'atlantis-vault',
    agentId: 'poseidon',
    connected: false,
    approvedControlledRunner: false,
    localOnly: true,
    usageAllowed: false,
    workerSpawnAllowed: false,
    lockedActions: [
      ...WORKSPACE_KERNEL_LOCKED_ACTIONS,
      'database write without DLV approval',
      'Obsidian write without DLV approval',
      'cross-domain worker routing through Poseidon as a bottleneck',
    ],
  },
]

export const WORKSPACE_BLUEPRINT_REGISTRY: Array<WorkspaceBlueprint> = [
  {
    blueprintId: 'atlantis-vault-governance-v1',
    version: '1.0.0',
    label: 'Atlantis Vault Governance',
    domain: 'data-vault',
    roomId: 'atlantis-vault',
    stationId: 'atlantis-index',
    acceptedIntents: ['atlantis vault', 'data vault', 'database audit', 'db audit', 'obsidian catalog', 'vault catalog', 'memory catalog'],
    inputKinds: ['freeform-text', 'url', 'local-path', 'generic-payload'],
    outputKinds: ['data-vault-audit-packet', 'obsidian-context-packet'],
    allowedToolIds: ['atlantis-vault-index', 'obsidian-context'],
    allowedWorkerProfileIds: ['controlled-poseidon-vault-v1', 'hermes-manager'],
    riskClass: 'R1_LOCAL_WRITE',
    approvalPolicy: approvalPolicy('required_for_live_action', 'Poseidon may inspect DB/Obsidian state; DB writes, Obsidian writes, and cleanup remain approval-gated.'),
    states: ['intake', 'routed', 'station_handoff', 'artifact_ready', 'approval', 'completed', 'blocked'],
    lockedActions: [
      ...WORKSPACE_KERNEL_LOCKED_ACTIONS,
      'database write without DLV approval',
      'Obsidian write without DLV approval',
      'bulk cleanup/delete without readback',
    ],
    defaultNextStep: 'Open Atlantis Vault, inspect real DB/Obsidian links, and show only data-backed health cards before any write or cleanup.',
  },
  {
    blueprintId: 'etsy-smart-product-intake-v1',
    version: '1.0.0',
    label: 'Etsy Smart Product Intake',
    domain: 'etsy',
    roomId: 'etsy-market-lab',
    stationId: 'etsy-loki-product-hunt',
    acceptedIntents: ['smart intake', 'dolaro product research', 'mixed source product intake'],
    inputKinds: ['freeform-text', 'url', 'local-path', 'image-ref', 'sheet-ref'],
    outputKinds: ['product-candidate-packet', 'selected-product-packet'],
    allowedToolIds: ['smart-intake-v2', 'etsy-product-gallery'],
    allowedWorkerProfileIds: ['hermes-manager', 'controlled-hermes-v1', 'controlled-scout-v2'],
    riskClass: 'R1_LOCAL_WRITE',
    approvalPolicy: approvalPolicy('required_for_live_action', 'Local intake is allowed; external reads and marketplace actions remain locked.'),
    states: ['intake', 'routed', 'station_handoff', 'artifact_ready', 'approval', 'completed', 'blocked'],
    lockedActions: WORKSPACE_KERNEL_LOCKED_ACTIONS,
    defaultNextStep: 'Open Product Search / Smart Intake V2 and stage the local mission packet.',
  },
  {
    blueprintId: 'etsy-live-readonly-research-v1',
    version: '1.0.0',
    label: 'Etsy Live Read-Only Research',
    domain: 'etsy',
    roomId: 'etsy-market-lab',
    stationId: 'etsy-loki-product-hunt',
    acceptedIntents: ['live read-only product research', 'etsy live scout', 'loki live scout'],
    inputKinds: ['freeform-text', 'url'],
    outputKinds: ['live-product-candidate-packet'],
    allowedToolIds: ['etsy-live-readonly-scout'],
    allowedWorkerProfileIds: ['controlled-scout-v2'],
    riskClass: 'R2_EXTERNAL_READ',
    approvalPolicy: approvalPolicy('required_for_live_action', 'Read-only research may be attempted only through the controlled Scout path; live actions remain locked.'),
    states: ['intake', 'routed', 'station_handoff', 'artifact_ready', 'completed', 'blocked'],
    lockedActions: WORKSPACE_KERNEL_LOCKED_ACTIONS,
    defaultNextStep: 'Run one controlled read-only scout or show the missing connector blocker in Product Search.',
  },
  {
    blueprintId: 'etsy-draft-prep-v1',
    version: '1.0.0',
    label: 'Etsy Draft Prep',
    domain: 'etsy',
    roomId: 'etsy-market-lab',
    stationId: 'etsy-odin-draft-approval',
    acceptedIntents: ['etsy draft prep', 'listing draft preview', 'draft approval'],
    inputKinds: ['product-packet', 'freeform-text'],
    outputKinds: ['etsy-draft-preview-packet', 'approval-packet'],
    allowedToolIds: ['shotlab-handoff', 'seo-workbench', 'approval-inbox'],
    allowedWorkerProfileIds: ['hermes-manager', 'controlled-hermes-v1'],
    riskClass: 'R3_EXTERNAL_WRITE',
    approvalPolicy: approvalPolicy('operator_required', 'Draft publication or live listing edits require explicit approval.'),
    states: ['routed', 'artifact_ready', 'approval', 'completed', 'blocked'],
    lockedActions: WORKSPACE_KERNEL_LOCKED_ACTIONS,
    defaultNextStep: 'Stage draft preview locally, then request approval before any live Etsy action.',
  },
  {
    blueprintId: 'shotlab-media-prep-v1',
    version: '1.0.0',
    label: 'ShotLab Media Prep',
    domain: 'shotlab',
    roomId: 'etsy-market-lab',
    stationId: 'etsy-thor-shotlab-prep',
    acceptedIntents: ['shotlab', 'media prep', 'image prep', 'visual generation'],
    inputKinds: ['product-packet', 'image-ref', 'freeform-text'],
    outputKinds: ['shotlab-handoff-packet'],
    allowedToolIds: ['shotlab-handoff'],
    allowedWorkerProfileIds: ['hermes-manager'],
    riskClass: 'R4_COST_OR_ACCOUNT',
    approvalPolicy: approvalPolicy('operator_required', 'Paid generation and account usage are locked in Kernel V1.'),
    states: ['routed', 'artifact_ready', 'approval', 'completed', 'blocked'],
    lockedActions: WORKSPACE_KERNEL_LOCKED_ACTIONS,
    defaultNextStep: 'Create a local media handoff packet; paid ShotLab generation remains locked.',
  },
  {
    blueprintId: 'seo-alura-keyword-v1',
    version: '1.0.0',
    label: 'SEO / Alura Keyword Packet',
    domain: 'seo-alura',
    roomId: 'etsy-market-lab',
    stationId: 'etsy-thor-seo-metrics',
    acceptedIntents: ['seo', 'alura', 'keyword', 'tags', 'title'],
    inputKinds: ['product-packet', 'freeform-text'],
    outputKinds: ['seo-packet'],
    allowedToolIds: ['seo-workbench'],
    allowedWorkerProfileIds: ['hermes-manager', 'controlled-scout-v2'],
    riskClass: 'R2_EXTERNAL_READ',
    approvalPolicy: approvalPolicy('required_for_live_action', 'Live Alura reads are not connected; missing metrics must be labeled.'),
    states: ['routed', 'artifact_ready', 'approval', 'completed', 'blocked'],
    lockedActions: WORKSPACE_KERNEL_LOCKED_ACTIONS,
    defaultNextStep: 'Stage a local SEO packet and label missing live metrics honestly.',
  },
  {
    blueprintId: 'supplier-proof-v1',
    version: '1.0.0',
    label: 'Supplier Proof Packet',
    domain: 'supplier',
    roomId: 'etsy-market-lab',
    stationId: 'etsy-thor-source-truth',
    acceptedIntents: ['supplier proof', 'factory verification', 'aliexpress supplier', 'alibaba supplier'],
    inputKinds: ['url', 'freeform-text', 'image-ref'],
    outputKinds: ['supplier-proof-packet'],
    allowedToolIds: [],
    allowedWorkerProfileIds: ['hermes-manager'],
    riskClass: 'R3_EXTERNAL_WRITE',
    approvalPolicy: approvalPolicy('operator_required', 'Supplier messages and purchases are locked.'),
    states: ['routed', 'artifact_ready', 'approval', 'completed', 'blocked'],
    lockedActions: WORKSPACE_KERNEL_LOCKED_ACTIONS,
    defaultNextStep: 'Create a local supplier proof packet; do not message or purchase.',
  },
  {
    blueprintId: 'cad-3d-print-design-v1',
    version: '1.0.0',
    label: 'CAD / 3D Print Design Packet',
    domain: 'cad-3d-print',
    roomId: 'terra-forge',
    stationId: 'terra-modeling-studio',
    acceptedIntents: ['cad', '3d print', 'stl', 'step', 'openscad', 'g-code'],
    inputKinds: ['freeform-text', 'local-path', 'image-ref'],
    outputKinds: ['cad-design-packet', 'print-prep-packet'],
    allowedToolIds: ['terra-modeling-studio', 'terra-model-hunt', 'terra-printer-control'],
    allowedWorkerProfileIds: ['hermes-manager', 'controlled-terra-v1', 'codex-ui-builder'],
    riskClass: 'R4_COST_OR_ACCOUNT',
    approvalPolicy: approvalPolicy('operator_required', 'Printer control and production remain locked.'),
    states: ['routed', 'artifact_ready', 'approval', 'completed', 'blocked'],
    lockedActions: WORKSPACE_KERNEL_LOCKED_ACTIONS,
    defaultNextStep: 'Stage a local CAD design packet in Terra Forge; printer control remains locked.',
  },
  {
    blueprintId: 'daily-news-content-v1',
    version: '1.0.0',
    label: 'Daily News / Content Packet',
    domain: 'content-news',
    roomId: 'gateway-cockpit',
    stationId: 'gateway-console',
    acceptedIntents: ['daily news', 'newspaper', 'briefing', 'content', 'video'],
    inputKinds: ['freeform-text', 'url'],
    outputKinds: ['news-brief-packet'],
    allowedToolIds: ['daily-news-board'],
    allowedWorkerProfileIds: ['hermes-manager'],
    riskClass: 'R3_EXTERNAL_WRITE',
    approvalPolicy: approvalPolicy('operator_required', 'Publishing or Discord delivery remains locked.'),
    states: ['routed', 'artifact_ready', 'approval', 'completed', 'blocked'],
    lockedActions: WORKSPACE_KERNEL_LOCKED_ACTIONS,
    defaultNextStep: 'Stage a local news/content packet; no Discord or scheduled send occurs.',
  },
  {
    blueprintId: 'discord-readback-v1',
    version: '1.0.0',
    label: 'Discord Readback Packet',
    domain: 'gateway-discord',
    roomId: 'gateway-cockpit',
    stationId: 'gateway-console',
    acceptedIntents: ['discord readback', 'remote control readback', 'send summary'],
    inputKinds: ['freeform-text', 'generic-payload'],
    outputKinds: ['discord-readback-packet'],
    allowedToolIds: [],
    allowedWorkerProfileIds: ['hermes-manager'],
    riskClass: 'R3_EXTERNAL_WRITE',
    approvalPolicy: approvalPolicy('operator_required', 'Discord sending is locked without an approved delivery path.'),
    states: ['routed', 'artifact_ready', 'approval', 'completed', 'blocked'],
    lockedActions: WORKSPACE_KERNEL_LOCKED_ACTIONS,
    defaultNextStep: 'Prepare local Discord readback preview; do not send.',
  },
  {
    blueprintId: 'generic-project-status-v1',
    version: '1.0.0',
    label: 'Generic Project Status Packet',
    domain: 'command',
    roomId: 'olympus-command',
    stationId: 'mission-router',
    acceptedIntents: ['project status', 'checkpoint', 'status update', 'blocker review', 'council', 'strategy round', 'general opinion'],
    inputKinds: ['freeform-text', 'generic-payload'],
    outputKinds: ['generic-workspace-packet'],
    allowedToolIds: ['command-room-manager'],
    allowedWorkerProfileIds: ['hermes-manager', 'council-julius', 'council-alexander', 'council-napoleon', 'council-saladin', 'council-genghis', 'council-hannibal'],
    riskClass: 'R0_LOCAL_VIEW',
    approvalPolicy: approvalPolicy('not_required', 'Local status readback has no live side effect.'),
    states: ['routed', 'artifact_ready', 'completed', 'blocked'],
    lockedActions: WORKSPACE_KERNEL_LOCKED_ACTIONS,
    defaultNextStep: 'Create a local project status packet.',
  },
  {
    blueprintId: 'approval-gate-v1',
    version: '1.0.0',
    label: 'Approval Gate',
    domain: 'approval',
    roomId: 'olympus-command',
    stationId: 'approval-dais',
    acceptedIntents: ['approval', 'publish', 'upload', 'purchase', 'paid action', 'live edit'],
    inputKinds: ['approval-request', 'freeform-text', 'generic-payload'],
    outputKinds: ['approval-packet'],
    allowedToolIds: ['approval-inbox'],
    allowedWorkerProfileIds: ['hermes-manager'],
    riskClass: 'R5_DESTRUCTIVE',
    approvalPolicy: approvalPolicy('operator_required', 'Live, paid, account, and destructive actions stop at approval.'),
    states: ['routed', 'approval', 'completed', 'blocked'],
    lockedActions: WORKSPACE_KERNEL_LOCKED_ACTIONS,
    defaultNextStep: 'Create an approval packet and keep the live action locked.',
  },
]

export function getWorkspaceBlueprintRegistry() {
  return WORKSPACE_BLUEPRINT_REGISTRY
}

export function getWorkspaceBlueprintById(blueprintId: WorkspaceBlueprintId) {
  return WORKSPACE_BLUEPRINT_REGISTRY.find((blueprint) => blueprint.blueprintId === blueprintId)
}
