#!/usr/bin/env bash
# Split the master ~/.hermes/.env into per-profile .env files with least privilege.
#
# Before: every profile's .env is a symlink to ~/.hermes/.env (all workers see all keys).
# After:  each profile gets a real .env (mode 600) containing only the keys it needs:
#   - ALL profiles:                       OLLAMA_API_KEY
#   - researcher:                         + GOOGLE_API_KEY
#   - ops-watch, quant-agent, concierge:  + API_SERVER_KEY (if present in master)
#   - Discord tokens:                     NO profile (gateway-only, stay in master)
#
# The master ~/.hermes/.env is never modified. Idempotent: re-running regenerates.
# Does not touch auth.json or its symlinks.

set -euo pipefail

HERMES_ROOT="${HERMES_ROOT:-$HOME/.hermes}"
MASTER="$HERMES_ROOT/.env"
PROFILES_DIR="$HERMES_ROOT/profiles"

[ -f "$MASTER" ] || { echo "master env not found: $MASTER" >&2; exit 1; }
[ -d "$PROFILES_DIR" ] || { echo "profiles dir not found: $PROFILES_DIR" >&2; exit 1; }

# get_value KEY -> prints the full "KEY=value" line from master (last wins), or nothing
get_line() {
  grep -E "^$1=" "$MASTER" | tail -n 1 || true
}

VAULT_PATH="${HERMES_KNOWLEDGE_VAULT:-$HOME/workspace/vault}"

keys_for_profile() {
  local profile="$1"
  local keys="OLLAMA_API_KEY"
  case "$profile" in
    researcher) keys="$keys GOOGLE_API_KEY" ;;
    ops-watch|quant-agent|concierge) keys="$keys API_SERVER_KEY" ;;
  esac
  echo "$keys"
}

for dir in "$PROFILES_DIR"/*/; do
  profile="$(basename "$dir")"
  envfile="$dir.env"

  # Remove symlink (or stale regular file) — we regenerate from scratch.
  rm -f "$envfile"

  tmp="$(mktemp "$dir.env.XXXXXX")"
  {
    echo "# Generated by swarm-split-creds.sh — do not edit; re-run the script instead."
    for key in $(keys_for_profile "$profile"); do
      line="$(get_line "$key")"
      # Only write keys that exist with a non-empty value in the master file.
      if [ -n "$line" ] && [ -n "${line#*=}" ]; then
        printf '%s\n' "$line"
      fi
    done
    # Knowledge-stewardship profiles get the Obsidian vault path (non-secret).
    case "$profile" in
      km-agent|concierge)
        printf 'OBSIDIAN_VAULT_PATH=%s\n' "$VAULT_PATH"
        printf 'HERMES_KNOWLEDGE_VAULT=%s\n' "$VAULT_PATH"
        ;;
    esac
  } > "$tmp"
  chmod 600 "$tmp"
  mv "$tmp" "$envfile"
  echo "wrote $envfile ($(grep -c '=' "$envfile" || true) keys)"
done
