#!/usr/bin/env bash
# Generate ~/.local/bin worker launcher wrappers for every worker in swarm.yaml.
#
# Two code paths look for these wrappers under different names:
#   - swarm-lifecycle.ts (renew path) expects ~/.local/bin/<workerId>
#   - swarm-dispatch.ts getWrapperPath() expects ~/.local/bin/<wrapper-field>
#     (e.g. "orchestrator:plan") and parses `cd <path> || exit 1` for cwd.
# We emit both names so either path resolves.
#
# Each wrapper launches `hermes chat --tui` with HERMES_HOME pinned to the
# worker profile. It does NOT exec — a crashed agent leaves a readable pane
# plus the exit sentinel instead of killing the tmux session.
#
# Usage: ./scripts/swarm-generate-wrappers.sh [repo_dir]
set -euo pipefail

REPO_DIR="${1:-$(cd "$(dirname "$0")/.." && pwd)}"
SWARM_YAML="$REPO_DIR/swarm.yaml"
BIN_DIR="$HOME/.local/bin"
HERMES_BIN="$HOME/.local/bin/hermes"
PROFILES_DIR="$HOME/.hermes/profiles"
WORKSPACE_ROOT="${HERMES_WORKSPACE_DIR:-$HOME/workspace}"
mkdir -p "$WORKSPACE_ROOT"

[ -f "$SWARM_YAML" ] || { echo "swarm.yaml not found at $SWARM_YAML" >&2; exit 1; }
mkdir -p "$BIN_DIR"

# Parse id + wrapper pairs from swarm.yaml (simple line scan; ids/wrappers are flat scalars).
current_id=""
declare -a PAIRS=()
while IFS= read -r line; do
  case "$line" in
    *"- id:"*)   current_id="$(echo "$line" | sed -E 's/.*- id:[[:space:]]*//; s/[[:space:]]*$//')" ;;
    *"wrapper:"*) wrapper="$(echo "$line" | sed -E 's/.*wrapper:[[:space:]]*//; s/[[:space:]]*$//')"
                 [ -n "$current_id" ] && PAIRS+=("$current_id|$wrapper") ;;
  esac
done < "$SWARM_YAML"

write_wrapper() {
  local path="$1" worker_id="$2"
  cat > "$path" <<EOF
#!/usr/bin/env bash
# AUTO-GENERATED by scripts/swarm-generate-wrappers.sh — do not edit by hand.
# Swarm worker launcher: $worker_id
#
# Two callers, two invocation shapes — the wrapper must serve both:
#   1. swarm-lifecycle tmuxStart runs the wrapper with NO args -> persistent TUI.
#   2. swarm-dispatch oneshot runs it as \`<wrapper> chat -q <prompt> ...\` and
#      expects the args forwarded to hermes. Hardcoding \`chat --tui\` here would
#      swallow those args, launch a TUI with no TTY, and fail every oneshot.
# So: forward "\$@" when given, default to the persistent TUI when not.
export HERMES_HOME="$PROFILES_DIR/$worker_id"
export HERMES_CLI_BIN="$HERMES_BIN"
# launchd-spawned callers have a minimal PATH; the Hermes TUI needs node
# (symlinked in ~/.local/bin).
export PATH="\$HOME/.local/bin:/opt/homebrew/bin:\$PATH"
# Canonical agent file space — worker output must land where the Files page
# looks. Task prompts that target a repo cd explicitly.
cd "$WORKSPACE_ROOT" || exit 1
if [ "\$#" -gt 0 ]; then
  exec "$HERMES_BIN" "\$@"
fi
"$HERMES_BIN" chat --tui
hermes_status=\$?
printf '\n[Hermes worker exited with status %s]\n' "\$hermes_status"
EOF
  chmod +x "$path"
}

count=0
for pair in "${PAIRS[@]}"; do
  worker_id="${pair%%|*}"
  wrapper="${pair##*|}"
  [ -x "$HERMES_BIN" ] || { echo "hermes bin missing at $HERMES_BIN" >&2; exit 1; }
  [ -d "$PROFILES_DIR/$worker_id" ] || echo "WARN: profile dir missing for $worker_id" >&2

  write_wrapper "$BIN_DIR/$worker_id" "$worker_id"
  if [ "$wrapper" != "$worker_id" ]; then
    write_wrapper "$BIN_DIR/$wrapper" "$worker_id"
  fi
  echo "wrote wrapper: $worker_id  ->  $BIN_DIR/$worker_id  +  $BIN_DIR/$wrapper"
  count=$((count + 1))
done

echo "Generated wrappers for $count workers."
